// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqdqbfqsnnetrjimkivv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxZHFiZnFzbm5ldHJqaW1raXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NzY3MTMsImV4cCI6MjA2ODQ1MjcxM30.s3efjtiEUaByavrRtA3V74L_aJgmhvqHzKpnq-8A220";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});